version: 2.1
executors:
  my-executor:
    docker:
      - image: gcc

jobs:
  test:
    executor: my-executor
    steps:
      - run: make test

jobs:
  build:
    executor: my-executor
    steps:
      - run: make
      
jobs:
  testbuild:
    docker:
      - image: gcc
    working_directory: ~
    branches:
      only:
        - master
    steps:
      - run: make test
      - run: make

