version: 2.1

executors:
  my-executor:
    docker:
      - image: gcc

jobs:
  test:
    executor: my-executor
    steps:
      - run: make test
      
  build:
    executor: my-executor
    steps:
      - run: make
