version: 2.1

executors:
  my-executor:
    docker:
      - image: gcc

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run: chmod 777 runSuite
      - run: make test
      - run: make
